### ISSUE TITLE
Unsafe Characters have to be escaped

### ISSUE THREAD

**Issue by ghost** [pamapa/python-fritzbox#1]
Fritz!Box 7490 showed an import error on an a saved file, due to the following Name:

<pre>
"Restaurant Royals & Rice"
</pre>

To get it working i had to escape the unsafe charakters (the '&') to

<pre>
"Restaurant Royals &amp;amp; Rice"
</pre>

As i use utf-8 encoding umlauts are no problem, only those Charakters, that are not safe as data in an XML.

**Comment by pamapa** [comment]
fixed
