### ISSUE TITLE
error: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by Oroo9CeL** [pamapa/python-fritzbox#7]
Does not work anymore:

Exported thunderbird 91.10.0 addressbook as ldif or csv.

$ fritzboxphonebook.py --load office.ldif --save office.xml --debug
load phonebook from ['office.ldif']
error: expected str, bytes or os.PathLike object, not list
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/python_fritzbox-0.2-py3.9.egg/EGG-INFO/scripts/fritzboxphonebook.py", line 100, in <module>
    ext = os.path.splitext(args.load)[1].lower()
  File "/usr/lib/python3.9/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by pamapa** [comment]
Thanks for using, i have now push stuff i did 8 month ago and forgot to push :-)

**Comment by Oroo9CeL** [comment]
Thanks for the bug fix. It seems to work now.  But now there is a new error with my LDIF file.

```
~$ fritzboxphonebook.py --load office.ldif --save office.xml --debug
load phonebook from office.ldif
error: Line 2: Not a valid string-representation for dn: 'cn=Huber, Hans'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/python_fritzbox-0.3-py3.9.egg/EGG-INFO/scripts/fritzboxphonebook.py", line 113, in <module>
    tmp = ldif.get_books(f, args.vip_groups, debug=args.debug)
  File "/usr/local/lib/python3.9/dist-packages/python_fritzbox-0.3-py3.9.egg/fritzbox/LDIF.py", line 126, in get_books
    parser.parse()
  File "/usr/lib/python3/dist-packages/ldif.py", line 461, in parse
    return self.parse_entry_records() # parse()
  File "/usr/lib/python3/dist-packages/ldif.py", line 430, in parse_entry_records
    raise ValueError('Line %d: Not a valid string-representation for dn: %s.' % (self.line_counter,repr(v)))
ValueError: Line 2: Not a valid string-representation for dn: 'cn=Huber, Hans'.
```

The office.ldif:

```
dn: cn=Huber, Hans
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
objectclass: mozillaAbPersonAlpha
givenName: Hans
sn: Huber
cn: Huber, Hans
modifytimestamp: 1643371063
mobile: +48 171 12345678

```

**Comment by pamapa** [comment]
The error you get is coming from the used python library `/usr/lib/python3/dist-packages/ldif.py`. Looks like you ldif file is not conformant (https://datatracker.ietf.org/doc/html/rfc2849). I do not see whats wrong with your entry...

**Comment by Oroo9CeL** [comment]
I have found the error. The RFC shows a valid dn:
dn: cn=Barbara Jensen, ou=Product Development, dc=airius, dc=com

So a comma is a separator here. In my LDIF this is not so:
dn: cn=Huber, Hans

If I omit or mask the comma, then it works:
dn: cn=Huber Hans or dn: cn=Huber\, Hans

So it looks like thunderbird does not generate an RFC compliant LDIF export here.

The question now is, if the dn is important for the xml conversion at all? Maybe you could skip reading the dn in your script?

Something else I noticed:
If there is only one phone number for a contact, then thunderbird exports it for .vcf like this:

TEL;VALUE=TEXT:+4817112345678

Your script then skips this entry when converting to .xml because TYPE=home or TYPE=work or TYPE=mobile is missing here. Maybe you could also catch this error from thunderbird and then assign the entry with missing classification then e.g. TYPE=home?

Thanks a lot!

**Comment by pamapa** [comment]
Which version of Thunderbird are you using? I never has the issue with the invalid ldif yet...

**Comment by Oroo9CeL** [comment]
91.11.0 (64-Bit)

**Comment by pamapa** [comment]
Re-added fallback when `TYPE` is not defined. The invalid ldif is another story. I do not yet know how we could fix this. Taught we could skip that entry, but it throws in the main parse function...

**Comment by Oroo9CeL** [comment]
Fine! .vcf conversion works now with a warning, when TYPE is not defined!
Because of the ldif Thunderbird error, I don't think it's your script's job to solve it.
I help myself by replacing the dn for all entries with a default value in the thunderbird export, before the conversion to XML.

```
sed 's/^dn:.*/dn: cn=a/g'
```
